title: My Resume
url: 'http://webjeda.com'
baseurl: '/first-web' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Parthiban Singaravelu
tagline: SAP Abap Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: prthysing@gmail.com
phone: 012 345 6789
linkedin: parthysing
github: parthysing
twitter: '@parthysing'



